# Generated by Django 5.2.5 on 2025-08-29 09:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company_Name')),
                ('company_type', models.CharField(choices=[('llc', 'LLC'), ('corporation', 'Corporation'), ('partnership', 'Partnership'), ('sole_proprietorship', 'Sole Proprietorship'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], max_length=50, verbose_name='Type')),
                ('state_of_formation', models.CharField(max_length=100, verbose_name='State_of_Formation')),
                ('ein', models.CharField(blank=True, max_length=20, null=True, verbose_name='EIN')),
                ('associated_client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Associated_Client')),
                ('clients', models.TextField(blank=True, null=True, verbose_name='Clients')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airtable_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Airtable ID')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpenAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='OpenAI API Key')),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=100, verbose_name='OpenAI Model')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperature')),
                ('max_tokens', models.IntegerField(default=1000, verbose_name='Max Tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'OpenAI Configuration',
                'verbose_name_plural': 'OpenAI Configurations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='message_images/')),
                ('extracted_content', models.TextField(blank=True, null=True, verbose_name='Extracted Text')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_response', models.TextField(blank=True, null=True, verbose_name='AI Response')),
                ('edited_response', models.TextField(blank=True, null=True, verbose_name='Edited Response')),
                ('final_response', models.TextField(blank=True, null=True, verbose_name='Final Response')),
                ('follow_up_question', models.TextField(blank=True, null=True, verbose_name='Follow-up Question')),
                ('conversation_history', models.JSONField(blank=True, null=True, verbose_name='Conversation History')),
                ('from_knowledge_base', models.BooleanField(default=False)),
                ('knowledge_base_id', models.CharField(blank=True, max_length=255, null=True)),
                ('saved_to_knowledge_base', models.BooleanField(default=False)),
                ('saved_to_airtable', models.BooleanField(default=False)),
                ('airtable_lead_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, default='Manual', max_length=50, null=True, verbose_name='Message Source')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='app.message')),
            ],
        ),
    ]
